# All non-trivial open source projects use CI ("continuous integration")
# services, which automatically run the tests on each git commit or
# pull request and provide that feedback to maintainers and contributors.
#
# The simplest of them is Travis, and this is a complete config file!
# Go to https://docs.travis-ci.com/user/tutorial/ for details on how
# to enable it on your GitHub repo.
#
# There are similar services available from other providers,
# including one built in to GitLab, but generally more complicated.

language: python
sudo: required
dist: xenial
python:
  - "3.6"
  - "3.7"
install:
  - pip install --upgrade pip setuptools
  - pip install -r requirements.txt
  - pip install .
script:
  - source check.sh
  - git diff --exit-code
