# GIMP Palette
# Name: 3Ai March 2019
# Columns: 1
# generated by Kathy Reid <kathy@kathyreid.id.au>
# based on originals supplied by 3Ai staff
# big ups to Dougie (Stephen Fry) for his help too
# 0   0   0    Black (#000000)
# 255 255 255  White (#FFFFFF)
# 51  51  51   3Ai.Grey (#333333)
# 140 181 197  3Ai.Dull Teal (#8CB5C5) (Pantone 536 C)
# 91  224 226  3Ai.Bright Aqua (#5BE0E2) (Pantone 305 C)
# 130 255 158  3Ai.Apple Green (#82FF9E) (Pantone 7487 C)
# 244 135 255  3Ai.Violet McKenzie (#F487FF) (Pantone 231 C)
# 104 15  119  3Ai.Deep Purple (#680F77) (Pantone 2613 C)

from sense_hat import SenseHat

sense = SenseHat()

# first row
sense.set_pixel(0, 0, (0, 0, 0))
sense.set_pixel(0, 1, (0, 0, 0))
sense.set_pixel(0, 2, (0, 0, 0))
sense.set_pixel(0, 3, (0, 0, 0))
sense.set_pixel(0, 4, (0, 0, 0))
sense.set_pixel(0, 5, (0, 0, 0))
sense.set_pixel(0, 6, (0, 0, 0))
sense.set_pixel(0, 7, (0, 0, 0))

# second row
sense.set_pixel(1, 0, (0, 0, 0))
sense.set_pixel(1, 1, (0, 0, 0))
sense.set_pixel(1, 2, (0, 0, 0))
sense.set_pixel(1, 3, (0, 0, 0))
sense.set_pixel(1, 4, (0, 0, 0))
sense.set_pixel(1, 5, (0, 0, 0))
sense.set_pixel(1, 6, (0, 0, 0))
sense.set_pixel(1, 7, (0, 0, 0))

# third row
sense.set_pixel(2, 0, (0, 0, 0))
sense.set_pixel(2, 1, (0, 0, 0))
sense.set_pixel(2, 2, (104, 15, 119))  # purple
sense.set_pixel(2, 3, (0, 0, 0))
sense.set_pixel(2, 4, (0, 0, 0))
sense.set_pixel(2, 5, (0, 0, 0))
sense.set_pixel(2, 6, (0, 0, 0))
sense.set_pixel(2, 7, (0, 0, 0))

# fourth row
sense.set_pixel(3, 0, (91, 224, 226))  # aqua
sense.set_pixel(3, 1, (91, 224, 226))  # aqua
sense.set_pixel(3, 2, (104, 15, 119))  # purple
sense.set_pixel(3, 3, (0, 0, 0))
sense.set_pixel(3, 4, (0, 0, 0))
sense.set_pixel(3, 5, (244, 135, 255))  # violet
sense.set_pixel(3, 6, (244, 135, 255))  # violet
sense.set_pixel(3, 7, (130, 255, 158))  # green

# fifth row
sense.set_pixel(4, 0, (104, 15, 119))  # purple
sense.set_pixel(4, 1, (104, 15, 119))  # purple
sense.set_pixel(4, 2, (91, 224, 226))  # aqua
sense.set_pixel(4, 3, (104, 15, 119))  # purple
sense.set_pixel(4, 4, (244, 135, 255))  # violet
sense.set_pixel(4, 5, (104, 15, 119))  # purple
sense.set_pixel(4, 6, (130, 255, 158))  # green
sense.set_pixel(4, 7, (244, 135, 255))  # violet

# sixth row
sense.set_pixel(5, 0, (104, 15, 119))  # purple
sense.set_pixel(5, 1, (0, 0, 0))
sense.set_pixel(5, 2, (104, 15, 119))  # purple
sense.set_pixel(5, 3, (91, 224, 226))  # aqua
sense.set_pixel(5, 4, (104, 15, 119))  # purple
sense.set_pixel(5, 5, (130, 255, 158))  # green
sense.set_pixel(5, 6, (244, 135, 255))  # violet
sense.set_pixel(5, 7, (0, 0, 0))

# seventh row
sense.set_pixel(6, 0, (0, 0, 0))
sense.set_pixel(6, 1, (0, 0, 0))
sense.set_pixel(6, 2, (0, 0, 0))
sense.set_pixel(6, 3, (104, 15, 119))  # purple
sense.set_pixel(6, 4, (130, 255, 158))  # green
sense.set_pixel(6, 5, (244, 135, 255))  # violet
sense.set_pixel(6, 6, (0, 0, 0))
sense.set_pixel(6, 7, (0, 0, 0))

# eighth row
sense.set_pixel(7, 0, (0, 0, 0))
sense.set_pixel(7, 1, (0, 0, 0))
sense.set_pixel(7, 2, (0, 0, 0))
sense.set_pixel(7, 3, (0, 0, 0))
sense.set_pixel(7, 4, (0, 0, 0))
sense.set_pixel(7, 5, (0, 0, 0))
sense.set_pixel(7, 6, (0, 0, 0))
sense.set_pixel(7, 7, (0, 0, 0))
